---
- name: Installing rbenv
  homebrew:
    name: rbenv
    
- name: Installing Ruby build
  homebrew:
    name: ruby-build

- name: Installing Ruby
  homebrew:
    name: ruby

- lineinfile: 
    path: "~/.bash_profile"
    regexp: "^eval \"$(rbenv init -)\""
    create: yes
    line: "eval \"$(rbenv init -)\""

- name: Check if zsh is installed
  stat:
    path: ~/.zshrc
  register: zsh_installed

- lineinfile: 
    path: "~/.zshrc"
    regexp: "^eval \"$(rbenv init -)\""
    create: yes
    line: "eval \"$(rbenv init -)\""
  when: zsh_installed.stat.exists == True