---

- name: Installing zsh
  homebrew:
    name: zsh

- name: Installing zsh completions
  homebrew:
    name: zsh-completions

- name: Installing tmux
  homebrew:
    name: tmux

- name: Installing readline
  homebrew:
    name: readline

- name: Installing xz
  homebrew:
    name: xz

- name: Installing fzf
  homebrew:
    name: fzf

- name: Installing ack
  homebrew:
    name: ack

- name: Installing tree
  homebrew:
    name: tree

- name: Installing vim
  homebrew:
    name: vim

- name: Cloning oh-my-zsh repository
  git: 
    repo: https://github.com/robbyrussell/oh-my-zsh.git 
    dest: ~/.oh-my-zsh

- name: Creating .zshrc configuration file
  shell: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

- name: Changing default shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: "/bin/zsh"
  become: yes
  when: js_homebrewpackage_zsh_enabled
