---
- name: Updating Homebrew
  homebrew:
    update_homebrew: yes
  # when: not is_CI

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: yes
  # when: not is_CI

- import_tasks: googlechrome.yml
  when: js_homebrewcask_googlechrome_enabled

- import_tasks: androidstudio.yml
  when: js_homebrewcask_androidstudio_enabled

- import_tasks: iterm2.yml
  when: js_homebrewcask_iterm2_enabled

- import_tasks: visualstudiocode.yml
  when: js_homebrewcask_visualstudiocode_enabled

- import_tasks: postman.yml
  when: js_homebrewcask_postman_enabled

- import_tasks: spotify.yml
  when: js_homebrewcask_spotify_enabled

- import_tasks: dashlane.yml
  when: js_homebrewcask_dashlane_enabled

- import_tasks: slack.yml
  when: js_homebrewcask_slack_enabled

- import_tasks: notion.yml
  when: js_homebrewcask_notion_enabled

- import_tasks: sketch.yml
  when: js_homebrewcask_sketch_enabled

- import_tasks: docker.yml
  when: js_homebrewcask_docker_enabled

- import_tasks: java.yml
  when: js_homebrewcask_java_enabled
