---
- name: Customize Jumpstart Installation
  hosts: system
  gather_facts: no
  

  vars_prompt:
    - name: js_understand_default
      prompt: "We will now go through Command Line Tools..."
      default: "ok"
      private: no
    - name: js_homebrewpackage_zsh_enabled
      prompt: "Would you like to install the Z shell (zsh)?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_zshtheme_spaceship_enabled
      prompt: "Would you like to set the Zsh theme to spaceship?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_python_enabled
      prompt: "Would you like to install Python?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_ruby_enabled
      prompt: "Would you like to install Ruby?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_rust_enabled
      prompt: "Would you like to install Rust?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_elixir_enabled
      prompt: "Would you like to install Elixir?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_golang_enabled
      prompt: "Would you like to install Golang?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_git_enabled
      prompt: "Would you like to install Git?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_aws_enabled
      prompt: "Would you like to install AWS?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_terraform_enabled
      prompt: "Would you like to install Terraform?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_node_enabled
      prompt: "Would you like to install NodeJS?"
      default: "yes"
      private: no
    - name: js_understand_default
      prompt: "We will now go through General Applications and Tools..."
      default: "ok"
      private: no
    - name: js_homebrewcask_googlechrome_enabled
      prompt: "Would you like to Install Google Chrome?"
      default: "yes"
      private: no
    - name: js_homebrewcask_iterm2_enabled
      prompt: "Would you like to install iTerm2?"
      default: "yes"
      private: no
    - name: js_homebrewcask_visualstudiocode_enabled
      prompt: "Would you like to install Visual Studio Code?"
      default: "yes"
      private: no
    - name: js_homebrewcask_androidstudio_enabled
      prompt: "Would you like to install Android Studio?"
      default: "yes"
      private: no
    - name: js_homebrewcask_slack_enabled
      prompt: "Would you like to install Slack?"
      default: "yes"
      private: no
    - name: js_homebrewcask_spotify_enabled
      prompt: "Would you like to install Spotify?"
      default: "yes"
      private: no
    - name: js_homebrewcask_postman_enabled
      prompt: "Would you like to install Postman?"
      default: "yes"
      private: no
    - name: js_homebrewcask_dashlane_enabled
      prompt: "Would you like to install Dashlane?"
      default: "yes"
      private: no
    - name: js_homebrewcask_notion_enabled
      prompt: "Would you like to install Notion?"
      default: "yes"
      private: no
    - name: js_homebrewcask_sketch_enabled
      prompt: "Would you like to install Sketch?"
      default: "yes"
      private: no
    - name: js_homebrewcask_docker_enabled
      prompt: "Would you like to install Docker?"
      default: "yes"
      private: no
    - name: js_homebrewcask_java_enabled
      prompt: "Would you like to install Java?"
      default: "yes"
      private: no

  tasks:
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zsh_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zsh_enabled: {{ js_homebrewpackage_zsh_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zshtheme_spaceship_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zshtheme_spaceship_enabled: {{ js_homebrewpackage_zshtheme_spaceship_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_python_enabled: (?:True|False)$"
        line: "js_homebrewpackage_python_enabled: {{ js_homebrewpackage_python_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_ruby_enabled: (?:True|False)$"
        line: "js_homebrewpackage_ruby_enabled: {{ js_homebrewpackage_ruby_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_elixir_enabled: (?:True|False)$"
        line: "js_homebrewpackage_elixir_enabled: {{ js_homebrewpackage_elixir_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_golang_enabled: (?:True|False)$"
        line: "js_homebrewpackage_golang_enabled: {{ js_homebrewpackage_golang_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_git_enabled: (?:True|False)$"
        line: "js_homebrewpackage_git_enabled: {{ js_homebrewpackage_git_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_terraform_enabled: (?:True|False)$"
        line: "js_homebrewpackage_terraform_enabled: {{ js_homebrewpackage_terraform_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_node_enabled: (?:True|False)$"
        line: "js_homebrewpackage_node_enabled: {{ js_homebrewpackage_node_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_googlechrome_enabled: (?:True|False)$"
        line: "js_homebrewcask_googlechrome_enabled: {{ js_homebrewcask_googlechrome_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_androidstudio_enabled: (?:True|False)$"
        line: "js_homebrewcask_androidstudio_enabled: {{ js_homebrewcask_androidstudio_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_iterm2_enabled: (?:True|False)$"
        line: "js_homebrewcask_iterm2_enabled: {{ js_homebrewcask_iterm2_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_visualstudiocode_enabled: (?:True|False)$"
        line: "js_homebrewcask_visualstudiocode_enabled: {{ js_homebrewcask_visualstudiocode_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_slack_enabled: (?:True|False)$"
        line: "js_homebrewcask_slack_enabled: {{ js_homebrewcask_slack_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_spotify_enabled: (?:True|False)$"
        line: "js_homebrewcask_spotify_enabled: {{ js_homebrewcask_spotify_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_notion_enabled: (?:True|False)$"
        line: "js_homebrewcask_notion_enabled: {{ js_homebrewcask_notion_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_sketch_enabled: (?:True|False)$"
        line: "js_homebrewcask_sketch_enabled: {{ js_homebrewcask_sketch_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_docker_enabled: (?:True|False)$"
        line: "js_homebrewcask_docker_enabled: {{ js_homebrewcask_docker_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_java_enabled: (?:True|False)$"
        line: "js_homebrewcask_java_enabled: {{ js_homebrewcask_java_enabled|bool }}"